# This is a workflow to run on opening of the pull request

name: CD

on:
  pull_request:
    type:
      - open
    branch:
      - dev
    
jobs:
  # Build and test
  ci:
#    uses: ./.github/workflows/ci.yml
    uses: ./.github/workflows/ci-fake.yml
    
  # Deploy to TestFlight
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - run: echo Deploy to TestFlight workflow run on CI ok
