# This is a reusable workflow that could be used as a stub instead of heavy real-life workflows

name: Fake CI Workflow Stub

on:
  workflow_call:
    inputs:
      finish_ok:
        type: boolean
        required: false
        default: true

jobs:
  # Pretend CI performed ok
  fail_if:
    if: ${{ !github.event.inputs.finish_ok }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Fake CI Workflow Stub FAILED')
    
    #if: success()
  ok:
    if: ${{ github.event.inputs.finish_ok }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Fake CI Workflow Stub finished OK')
