# This is a reusable workflow that could be used as a stub instead of heavy real-life workflows

name: Fake CI Workflow Stub

on:
  workflow_call:

jobs:
  # Pretend CI performed ok
  ok:
    runs-on: ubuntu-latest
    steps:
      - run: echo Fake CI Workflow Stub finished OK
