# This is a reusable workflow that could be used as a stub instead of heavy real-life workflows

name: Fake CI Workflow Stub

on:
  workflow_call:

jobs:
  # Pretend CI performed ok
  fake-ci:
    if: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Fake CI Workflow Stub FAILSED')
    
    if: success()
      - run: echo Pretending CI performed ok
