# THIS IS WIP: LOOKING FOR A WAY TO USE INPUT PARAMETER DETERMINING DESIRED OUTCOME

# This is a reusable workflow that could be used as a stub instead of heavy real-life workflows

name: Fake CI Workflow Stub

on:
  workflow_call:
    inputs:
      finish_ok:
        description: 'Should workflow finish normally (true) or fail (false).'
        type: boolean
        required: false
        default: true

jobs:
  # Pretend CI performed ok
  fail_if:
    if: ${{ ! inputs.finish_ok }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Fake CI Workflow Stub FAILED')
    
    #if: success()
  ok:
    if: ${{ inputs.finish_ok }}
    runs-on: ubuntu-latest
    steps:
      - run: echo Fake CI Workflow Stub finished OK
