# This is to test calling a reusable workflow
#
# Reusing workflows - GitHub Docs
# https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: ci-fake

on:
  workflow_call:

jobs:
  # Pretend CI performed ok
  fake-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/ci-fake
      - run: echo Pretending CI performed ok
