
name: test_branch_filters

on:
  pull_request:
    types:
      - opened
    branches:
      - dev

jobs:
  run_if:
  # Triggers the workflow on push events for the "feature" and `fix` branches only
   if: startsWith(github.head_ref, 'feature/**' | 'fix/**')
   runs-on: ubuntu-latest
      steps:
          - run: echo push from feature or fix branch
